### PR TITLE
Add community bootnode address (#20)

### PR DESCRIPTION
**Pull request by JuManjey**
Co-authored-by: Brendan Playford <34052452+teslashibe@users.noreply.github.com>
Hello. I have a few nodes:

admin.addPeer("enode://51846037004a1e50958d84b0f5d8fde5c300187a54494fb5e215497acae59d7d2c1f61259b36c80126ccce09e2743f684dd933b998d74f84faaf7a0820e6d790@65.21.121.69:21000")

admin.addPeer("enode://8174e0f80c6fd2b2ce5e0397ffac2735d1e7167edce14474cead7f61e8851e025ade36d313949ec823489d3121e946a07e6751e68febc2ee1070e05271055cce@65.108.108.247:21000")

admin.addPeer("enode://8dc0c8c302a7da774cf8a25eb993aad97efc941dfbff442b9c4d4ed2d3f0e02883c5cb50acf73bab676bf8e6b634b2cb8c7c0172a399c7064e7491226b9d1ee7@65.21.72.147:21000")

admin.addPeer("enode://f4596869310c039ca6a07899e9062a63fa22c6ec7b2fce8bb83913c55a08ebe32a0cbce6eddae126660cabbed4cf893cb64d712a49f7d18464fc96ed2f81c507@142.132.146.169:21000")

admin.addPeer("enode://c197862d4fa7325565b466189ede79587dabdda0ca82921a7560029315e820aacd2e53f855228984e0bb71545237d9d02786f7360cbc3c0fc140df7a5121a4b9@65.21.224.199:21000?discport=41306")

admin.addPeer("enode://d1b0d78cb6942f081531063e827b900c5884687f13470adcae317990c9fd170908e09cbaeb5cb4abc5d5982c3bc68c0145dc38436cf6abc9580b5e88e678d7f1@65.108.127.24:21000")

admin.addPeer("enode://61b7dd5149e9c9554f2535354b6f4ede3455929ceb610cc1f033a09cdb458b6aedbc54e06ebcac7c154185efef80320066ce12dc6eb775d461aad8e715ef60fe@65.21.131.58:21000")

admin.addPeer("enode://ab00488ef44267628df414756db1174761485c76a88a23c1fd1475717f93530a1fa7c2621a3b55f40a930b847a84bedb67627bc335d54a15adf588bd05f46fd9@65.108.109.162:21000")

admin.addPeer("enode://0a65f145c007313dc2cb672bf380abedca22f197868b2900d386289c9f0634f4fe8ebe791a1a80b36e347e04886062a54f0d66dc8a4216961bd5621ba5d4a748@65.108.121.245:21000")

admin.addPeer("enode://8ca09502a18b5296880a946672a7ae771c4787744a3cf90431be965304e590213f4716e549d1e0a9edded81d2e6e5fc9a4f750906c832d6a6f107dfcba1a1e69@65.21.137.115:21000")

### CODE REVIEW

**Comment by leonfish777** [comment]
add my bootnode please! admin.addPeer("enode://dba12aa74c3813b6c08be1d534a6b9247447c054f103994212fa5c151907a20292a609f14bc59fbe19a77c7c72f1a5c511ad1e779f4261e549c5d7eca712d3d7@95.217.134.242:21000")

**Comment by ImNotDoneYet** [comment]
Add me please !

admin.addPeer("enode://a5f5d355b8d140795e5faba2710082d502ac784cad5011492dc7ebe3022697e33fb3d4c074dfc3cca6b53c28f497a64b384d173429cc5adbd9da8b4dda826afd@70.34.217.165:21000")

**Comment by TreshKilling** [comment]
add my bootnode please!
admin.addPeer("enode://2cd0ee8aba8f7386ef440ed616730c5b1dc4066468d4c4155f60454a606d3094e96c53b06c6d9ea13a667f3af478e7e5639752359796ad43b6cb63b172234c0f@83.171.248.44:21000")

**Comment by yuran8shon** [comment]
Hi, add my bootnodes

admin.addPeer("enode://833df0d956d24733c952b7d5c8d973f4e7aba9b414e01c2898a99e237ef9d0                                                         4c2f3379d89ec8dc18e558049b2910e3d8c0c6862606091bc6743757e435260f6e@185.215.167.21:21000")

admin.addPeer("enode://a1322a8061b080a98d1c2c9da2b2f3d98ce9f688cd3301c1757f0bc53702de                                         88b21320ec1b8ef0f7045a8228671197076991c0436b3642b8ae6840677307dcb4@62.171.164.178:21000")

**Comment by VFR24** [comment]
Hi, add my bootnodes
admin.addPeer("enode://74d49cb6c4f855e9d1f87f2e284f54c37346bbb5daa4830a7985c6ae67efac0583f962c094921b3ea446ef55a691b5c88fd2a0b3a04dbdc491bf6081d9650995@157.90.124.173:21000")

**Comment by peerlessDJ** [comment]
enode://7d02947c4b548f3a49129821e10b92a92c3291c860ccaf695f6b046dbc747c0fe27e5b031ecbaa2a7f04186fd4873e8ce944f7637914ec614ef2b86deb2a3767@122.112.243.15:30300

enode://0adeae14e5b77c236c87f849e6aca489fcce2a29794c1005833e8ba014df8f4fbd6e02bf957acb54d63ccb5e6f7c3b1ce4af0d25a7d449d56c0794e11005b768@121.36.213.132:30300

**Comment by Sheicer** [comment]
"enode://ee05b966fcafe7ffd1a6490268484b4fb0448dd786affd1266d67c94b7eb720e31963638b9dc7885940913a2fdc6f94c97f94cc5a40b4ff72b3ed2aa38784997@77.244.66.222:30300"

**Comment by Mikusha** [comment]
Hi, add my bootnode please

admin.addPeer("enode://8aeb20400009d2fb4a947c959bd658e393b7c13007a9ce76229527da859e0bfc535a25805fb5848e89041b89da1c783c26e12a10eb66590e7c6131f0bd8e04c1@168.119.117.224:21000")

**Comment by Diamalka** [comment]
Доброго, добавьте пожалуйста

enode://12d25d600c810ffab73508f616d001194dd46ccd02b4560b2c29be7c3e4f713e154fa350cf4b1a949c59ed392a61e82617a384fb548653f8b5f47ccef274fa502.354.109:

**Pull request closed without merging**
