### PR TITLE
New boot node

### PR DESCRIPTION
**Pull request by arkhiiipov**
admin.addPeer("enode://ede91c3f91059c22f7518f1493dcb7b703e0a8611bfdf91d131221e212912cb308e0cf23c6f9156eb00b21d5b1f7f5ecc3625583cb777d4fb8a78273620985f6@94.250.201.137:30300")

### CODE REVIEW

**Comment by arkhiiipov** [comment]
ADD BOOTNODE

**Comment by leonfish777** [comment]
add my bootnode please! admin.addPeer("enode://dba12aa74c3813b6c08be1d534a6b9247447c054f103994212fa5c151907a20292a609f14bc59fbe19a77c7c72f1a5c511ad1e779f4261e549c5d7eca712d3d7@95.217.134.242:21000")

**Comment by peerlessDJ** [comment]
add my bootnode please!

admin.addPeer("enode://7d02947c4b548f3a49129821e10b92a92c3291c860ccaf695f6b046dbc747c0fe27e5b031ecbaa2a7f04186fd4873e8ce944f7637914ec614ef2b86deb2a3767@122.112.243.15:30300")

**Comment by Misha-1908** [comment]
enode://19ebfb2560518f472d583eb4ad961896ca2d56245e0e5c99bb09438bf5970e820edce9f05271c62a98985861ba8db2c8698a8579fd24998935e5b1c9e504f26d@185.197.195.144:30300

**Comment by satman81** [comment]
admin.addPeer("enode://0eb7a3ec302fbc5945e78ba4f4b8a9df9f9788ca4c8970fa25f8bdd79ad73064caff5ac4dbba6550ce83fc8b4958d6152f4719475ed9adac2084a98e249119dd@83.171.249.107:21000")

**Comment by YaroslavShl** [comment]
Please Add my enode as a bootnode
"enode://52f736e778b1db7ece0ea2d20e1d2979db88456e7e8392abd7fb2c1bea7b73346a40de97e43615d3baac50b9bae2c16f1b156dd3c41dffd547eaaa6670ca992e@188.120.238.54:30300"

**Pull request closed without merging**
