### PR TITLE
add community bootnode 

### PR DESCRIPTION
**Pull request by TreshKilling**
admin.addPeer("enode://2cd0ee8aba8f7386ef440ed616730c5b1dc4066468d4c4155f60454a606d3094e96c53b06c6d9ea13a667f3af478e7e5639752359796ad43b6cb63b172234c0f@83.171.248.44:21000")

### CODE REVIEW

**Comment by peerlessDJ** [comment]
enode://7d02947c4b548f3a49129821e10b92a92c3291c860ccaf695f6b046dbc747c0fe27e5b031ecbaa2a7f04186fd4873e8ce944f7637914ec614ef2b86deb2a3767@122.112.243.15:30300

**Comment by MarcusDMT** [comment]
admin.addPeer("enode://7bcc04b443fadfef77ab394908f6f5c090ce804064382545e9e135439fcf3fd025ebe4e3af55768db58096ba61462a34e4b9fc8bf3696157d8de393177fd2c43@173.249.7.166:30300")

**Comment by izlychenue** [comment]
"enode://64a578e8d8a2d5031246b5a8171f6f80b69395dff1cfcc752bde833311042b03ed4e61ea611718fc4ea2142683e60b0fba6685b4e8ef9621dc0975189e8e4390@127.0.0.1:21000"

**Comment by fmcatalan** [comment]
admin.addPeer("enode://d0afa2cdea5ffa22d6e3a5b0ceb43ceb24ed27bd3be8f59404ad3daf5f4dbb72dcfa6c3db5cd257616325b3beb2fc20effa2bea0a6df8a1f6041762a8d35c254@:21000")

**Comment by fmcatalan** [comment]
admin.addPeer("enode://d0afa2cdea5ffa22d6e3a5b0ceb43ceb24ed27bd3be8f59404ad3daf5f4dbb72dcfa6c3db5cd257616325b3beb2fc20effa2bea0a6df8a1f6041762a8d35c254@190.231.184.46:21000")

**Comment by YaroslavShl** [comment]
Please Add my enode as a bootnode
"enode://52f736e778b1db7ece0ea2d20e1d2979db88456e7e8392abd7fb2c1bea7b73346a40de97e43615d3baac50b9bae2c16f1b156dd3c41dffd547eaaa6670ca992e@188.120.238.54:30300"

**Comment by teslashibe** [comment]
We will test bootnodes and add them to a new clean PR once v1.03 has been released

**Pull request merged**
